#!/usr/bin/env python

import random 
i=0

random_number = random.randint(1,10)
while i<999:
    i=i+1   
    guessed_number = int(raw_input('Guess an integer bwetween 1 and 10: '))
    if int(guessed_number) != int(random_number):
        x=guessed_number - random_number
        if x >0:
            print "Guess is too high"
        else:
            print "Guess is too low"
    else:
        print "You guessed it"
        i = 1000
