#!/usr/bin/env python
import RPi.GPIO as GPIO
import time
import random 

GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)
buzz_pin=32
led_pin=11

GPIO.setup(buzz_pin,GPIO.OUT)
GPIO.setup(led_pin,GPIO.OUT)

i=0

random_number = random.randint(1,10)
while i<999:
    i=i+1   
    guessed_number = int(raw_input('Guess an integer bwetween 1 and 10: '))
    if int(guessed_number) != int(random_number):
        Buzz=GPIO.PWM(buzz_pin,1000)
        Buzz.ChangeFrequency(440)
        Buzz.start(50)
        time.sleep(1)
        Buzz.stop()
        x=guessed_number - random_number
        if x >0:
            print "Guess is too high"
        else:
            print "Guess is too low"
    else:
        print "You guessed it"
        GPIO.output(led_pin,True)
        time.sleep(2)
        GPIO.output(led_pin,False)
        i = 1000
GPIO.cleanup()
